/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SaraCookbookIndexImport } from './routes/SaraCookbook/index'

// Create Virtual Routes

const SaraCookbookWheelLazyImport = createFileRoute('/SaraCookbook/wheel')()
const SaraCookbookSoupLazyImport = createFileRoute('/SaraCookbook/soup')()
const SaraCookbookSandwichLazyImport = createFileRoute(
  '/SaraCookbook/sandwich',
)()
const SaraCookbookPastaLazyImport = createFileRoute('/SaraCookbook/pasta')()
const SaraCookbookEntreeLazyImport = createFileRoute('/SaraCookbook/entree')()
const SaraCookbookDrinksLazyImport = createFileRoute('/SaraCookbook/drinks')()
const SaraCookbookDessertLazyImport = createFileRoute('/SaraCookbook/dessert')()
const SaraCookbookCuisineLazyImport = createFileRoute('/SaraCookbook/cuisine')()

// Create/Update Routes

const SaraCookbookIndexRoute = SaraCookbookIndexImport.update({
  id: '/SaraCookbook/',
  path: '/SaraCookbook/',
  getParentRoute: () => rootRoute,
} as any)

const SaraCookbookWheelLazyRoute = SaraCookbookWheelLazyImport.update({
  id: '/SaraCookbook/wheel',
  path: '/SaraCookbook/wheel',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/SaraCookbook/wheel.lazy').then((d) => d.Route),
)

const SaraCookbookSoupLazyRoute = SaraCookbookSoupLazyImport.update({
  id: '/SaraCookbook/soup',
  path: '/SaraCookbook/soup',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/SaraCookbook/soup.lazy').then((d) => d.Route),
)

const SaraCookbookSandwichLazyRoute = SaraCookbookSandwichLazyImport.update({
  id: '/SaraCookbook/sandwich',
  path: '/SaraCookbook/sandwich',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/SaraCookbook/sandwich.lazy').then((d) => d.Route),
)

const SaraCookbookPastaLazyRoute = SaraCookbookPastaLazyImport.update({
  id: '/SaraCookbook/pasta',
  path: '/SaraCookbook/pasta',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/SaraCookbook/pasta.lazy').then((d) => d.Route),
)

const SaraCookbookEntreeLazyRoute = SaraCookbookEntreeLazyImport.update({
  id: '/SaraCookbook/entree',
  path: '/SaraCookbook/entree',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/SaraCookbook/entree.lazy').then((d) => d.Route),
)

const SaraCookbookDrinksLazyRoute = SaraCookbookDrinksLazyImport.update({
  id: '/SaraCookbook/drinks',
  path: '/SaraCookbook/drinks',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/SaraCookbook/drinks.lazy').then((d) => d.Route),
)

const SaraCookbookDessertLazyRoute = SaraCookbookDessertLazyImport.update({
  id: '/SaraCookbook/dessert',
  path: '/SaraCookbook/dessert',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/SaraCookbook/dessert.lazy').then((d) => d.Route),
)

const SaraCookbookCuisineLazyRoute = SaraCookbookCuisineLazyImport.update({
  id: '/SaraCookbook/cuisine',
  path: '/SaraCookbook/cuisine',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/SaraCookbook/cuisine.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/SaraCookbook/cuisine': {
      id: '/SaraCookbook/cuisine'
      path: '/SaraCookbook/cuisine'
      fullPath: '/SaraCookbook/cuisine'
      preLoaderRoute: typeof SaraCookbookCuisineLazyImport
      parentRoute: typeof rootRoute
    }
    '/SaraCookbook/dessert': {
      id: '/SaraCookbook/dessert'
      path: '/SaraCookbook/dessert'
      fullPath: '/SaraCookbook/dessert'
      preLoaderRoute: typeof SaraCookbookDessertLazyImport
      parentRoute: typeof rootRoute
    }
    '/SaraCookbook/drinks': {
      id: '/SaraCookbook/drinks'
      path: '/SaraCookbook/drinks'
      fullPath: '/SaraCookbook/drinks'
      preLoaderRoute: typeof SaraCookbookDrinksLazyImport
      parentRoute: typeof rootRoute
    }
    '/SaraCookbook/entree': {
      id: '/SaraCookbook/entree'
      path: '/SaraCookbook/entree'
      fullPath: '/SaraCookbook/entree'
      preLoaderRoute: typeof SaraCookbookEntreeLazyImport
      parentRoute: typeof rootRoute
    }
    '/SaraCookbook/pasta': {
      id: '/SaraCookbook/pasta'
      path: '/SaraCookbook/pasta'
      fullPath: '/SaraCookbook/pasta'
      preLoaderRoute: typeof SaraCookbookPastaLazyImport
      parentRoute: typeof rootRoute
    }
    '/SaraCookbook/sandwich': {
      id: '/SaraCookbook/sandwich'
      path: '/SaraCookbook/sandwich'
      fullPath: '/SaraCookbook/sandwich'
      preLoaderRoute: typeof SaraCookbookSandwichLazyImport
      parentRoute: typeof rootRoute
    }
    '/SaraCookbook/soup': {
      id: '/SaraCookbook/soup'
      path: '/SaraCookbook/soup'
      fullPath: '/SaraCookbook/soup'
      preLoaderRoute: typeof SaraCookbookSoupLazyImport
      parentRoute: typeof rootRoute
    }
    '/SaraCookbook/wheel': {
      id: '/SaraCookbook/wheel'
      path: '/SaraCookbook/wheel'
      fullPath: '/SaraCookbook/wheel'
      preLoaderRoute: typeof SaraCookbookWheelLazyImport
      parentRoute: typeof rootRoute
    }
    '/SaraCookbook/': {
      id: '/SaraCookbook/'
      path: '/SaraCookbook'
      fullPath: '/SaraCookbook'
      preLoaderRoute: typeof SaraCookbookIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/SaraCookbook/cuisine': typeof SaraCookbookCuisineLazyRoute
  '/SaraCookbook/dessert': typeof SaraCookbookDessertLazyRoute
  '/SaraCookbook/drinks': typeof SaraCookbookDrinksLazyRoute
  '/SaraCookbook/entree': typeof SaraCookbookEntreeLazyRoute
  '/SaraCookbook/pasta': typeof SaraCookbookPastaLazyRoute
  '/SaraCookbook/sandwich': typeof SaraCookbookSandwichLazyRoute
  '/SaraCookbook/soup': typeof SaraCookbookSoupLazyRoute
  '/SaraCookbook/wheel': typeof SaraCookbookWheelLazyRoute
  '/SaraCookbook': typeof SaraCookbookIndexRoute
}

export interface FileRoutesByTo {
  '/SaraCookbook/cuisine': typeof SaraCookbookCuisineLazyRoute
  '/SaraCookbook/dessert': typeof SaraCookbookDessertLazyRoute
  '/SaraCookbook/drinks': typeof SaraCookbookDrinksLazyRoute
  '/SaraCookbook/entree': typeof SaraCookbookEntreeLazyRoute
  '/SaraCookbook/pasta': typeof SaraCookbookPastaLazyRoute
  '/SaraCookbook/sandwich': typeof SaraCookbookSandwichLazyRoute
  '/SaraCookbook/soup': typeof SaraCookbookSoupLazyRoute
  '/SaraCookbook/wheel': typeof SaraCookbookWheelLazyRoute
  '/SaraCookbook': typeof SaraCookbookIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/SaraCookbook/cuisine': typeof SaraCookbookCuisineLazyRoute
  '/SaraCookbook/dessert': typeof SaraCookbookDessertLazyRoute
  '/SaraCookbook/drinks': typeof SaraCookbookDrinksLazyRoute
  '/SaraCookbook/entree': typeof SaraCookbookEntreeLazyRoute
  '/SaraCookbook/pasta': typeof SaraCookbookPastaLazyRoute
  '/SaraCookbook/sandwich': typeof SaraCookbookSandwichLazyRoute
  '/SaraCookbook/soup': typeof SaraCookbookSoupLazyRoute
  '/SaraCookbook/wheel': typeof SaraCookbookWheelLazyRoute
  '/SaraCookbook/': typeof SaraCookbookIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/SaraCookbook/cuisine'
    | '/SaraCookbook/dessert'
    | '/SaraCookbook/drinks'
    | '/SaraCookbook/entree'
    | '/SaraCookbook/pasta'
    | '/SaraCookbook/sandwich'
    | '/SaraCookbook/soup'
    | '/SaraCookbook/wheel'
    | '/SaraCookbook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/SaraCookbook/cuisine'
    | '/SaraCookbook/dessert'
    | '/SaraCookbook/drinks'
    | '/SaraCookbook/entree'
    | '/SaraCookbook/pasta'
    | '/SaraCookbook/sandwich'
    | '/SaraCookbook/soup'
    | '/SaraCookbook/wheel'
    | '/SaraCookbook'
  id:
    | '__root__'
    | '/SaraCookbook/cuisine'
    | '/SaraCookbook/dessert'
    | '/SaraCookbook/drinks'
    | '/SaraCookbook/entree'
    | '/SaraCookbook/pasta'
    | '/SaraCookbook/sandwich'
    | '/SaraCookbook/soup'
    | '/SaraCookbook/wheel'
    | '/SaraCookbook/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SaraCookbookCuisineLazyRoute: typeof SaraCookbookCuisineLazyRoute
  SaraCookbookDessertLazyRoute: typeof SaraCookbookDessertLazyRoute
  SaraCookbookDrinksLazyRoute: typeof SaraCookbookDrinksLazyRoute
  SaraCookbookEntreeLazyRoute: typeof SaraCookbookEntreeLazyRoute
  SaraCookbookPastaLazyRoute: typeof SaraCookbookPastaLazyRoute
  SaraCookbookSandwichLazyRoute: typeof SaraCookbookSandwichLazyRoute
  SaraCookbookSoupLazyRoute: typeof SaraCookbookSoupLazyRoute
  SaraCookbookWheelLazyRoute: typeof SaraCookbookWheelLazyRoute
  SaraCookbookIndexRoute: typeof SaraCookbookIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  SaraCookbookCuisineLazyRoute: SaraCookbookCuisineLazyRoute,
  SaraCookbookDessertLazyRoute: SaraCookbookDessertLazyRoute,
  SaraCookbookDrinksLazyRoute: SaraCookbookDrinksLazyRoute,
  SaraCookbookEntreeLazyRoute: SaraCookbookEntreeLazyRoute,
  SaraCookbookPastaLazyRoute: SaraCookbookPastaLazyRoute,
  SaraCookbookSandwichLazyRoute: SaraCookbookSandwichLazyRoute,
  SaraCookbookSoupLazyRoute: SaraCookbookSoupLazyRoute,
  SaraCookbookWheelLazyRoute: SaraCookbookWheelLazyRoute,
  SaraCookbookIndexRoute: SaraCookbookIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/SaraCookbook/cuisine",
        "/SaraCookbook/dessert",
        "/SaraCookbook/drinks",
        "/SaraCookbook/entree",
        "/SaraCookbook/pasta",
        "/SaraCookbook/sandwich",
        "/SaraCookbook/soup",
        "/SaraCookbook/wheel",
        "/SaraCookbook/"
      ]
    },
    "/SaraCookbook/cuisine": {
      "filePath": "SaraCookbook/cuisine.lazy.tsx"
    },
    "/SaraCookbook/dessert": {
      "filePath": "SaraCookbook/dessert.lazy.tsx"
    },
    "/SaraCookbook/drinks": {
      "filePath": "SaraCookbook/drinks.lazy.tsx"
    },
    "/SaraCookbook/entree": {
      "filePath": "SaraCookbook/entree.lazy.tsx"
    },
    "/SaraCookbook/pasta": {
      "filePath": "SaraCookbook/pasta.lazy.tsx"
    },
    "/SaraCookbook/sandwich": {
      "filePath": "SaraCookbook/sandwich.lazy.tsx"
    },
    "/SaraCookbook/soup": {
      "filePath": "SaraCookbook/soup.lazy.tsx"
    },
    "/SaraCookbook/wheel": {
      "filePath": "SaraCookbook/wheel.lazy.tsx"
    },
    "/SaraCookbook/": {
      "filePath": "SaraCookbook/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
